### ISSUE TITLE
Interface to dftd4

### ISSUE THREAD

**Issue by sunqm** [pyscf/dftd3#3]
See relevant discussions in
https://github.com/pyscf/pyscf/issues/983
https://github.com/dftd4/dftd4/issues/107

**Comment by awvwgk** [comment]
Trying to implement an interface like provided here in https://github.com/awvwgk/simple-dftd3/pull/17, if this works as expected I can implement it for DFT-D4 as well. The linked implementation in `dftd3.pyscf` should provide a drop-in replacement of `pyscf.dftd3.itrf`.

This interface could be forwarded here using

```python
# pyscf.dftd3
import dftd3.pyscf as itrf
dftd3 = itrf.dftd3
grad = itrf.grad
```

Only feature not supported is DFT-D2.

**Comment by gkc1000** [comment]
Looks interesting - perhaps you might be interested in the upcoming pyscf
developer's meeting (see link on pyscf github page).

**Comment by awvwgk** [comment]
Should be usable now, instructions for [`dftd3.pyscf`](https://github.com/awvwgk/simple-dftd3/blob/main/python/README.rst#pyscf-support) and [`dftd4.pyscf`](https://github.com/dftd4/dftd4/tree/main/python#pyscf-support) are up now. Since the change affects only the Python bindings the latest trunk can be built against the binary distribution from conda-forge for testing as described in the linked README files.

I can send a patch to forward the DFT-D4 / DFT-D3 integration here or update the pyscf.org webpage to directly point to the upstream repositories. Any preferences?

**Comment by sunqm** [comment]
Since the dftd3 dftd4 pyscf interface is available, can I disable this extension and add a message to redirect to the dftd3 and dftd4 native modules? @awvwgk

**Comment by jeanwsr** [comment]
I think we still need a wrapper to provide the total energy and grad -- with simple-dftd3 you only get the part from d3. Thus users can do something like `mf = to_dftd3(mf)`. That's what [ajz34/vdw](https://github.com/ajz34/vdw) do (including wrapper for dftd4). 

We are planning to contribute that to pyscf-forge.

**Comment by awvwgk** [comment]
This wrappers are already provided in both `dftd4.pyscf` and `dftd3.pyscf` by using the `energy` and `grad` functions:

```python
>>> from pyscf import gto, scf
>>> import dftd3.pyscf as d3
>>> mol = gto.M(
...     atom="""
...          O  -1.65542061  -0.12330038   0.00000000
...          O   1.24621244   0.10268870   0.00000000
...          H  -0.70409026   0.03193167   0.00000000
...          H  -2.03867273   0.75372294   0.00000000
...          H   1.57598558  -0.38252146  -0.75856129
...          H   1.57598558  -0.38252146   0.75856129
...          """
... )
>>> grad = d3.energy(scf.RHF(mol)).run().nuc_grad_method()
converged SCF energy = -149.947191000075
```

Or are you looking for something else?

**Comment by jeanwsr** [comment]
> This wrappers are already provided in both `dftd4.pyscf` and `dftd3.pyscf` by using the `energy` and `grad` functions:
> 
> ```python
> >>> from pyscf import gto, scf
> >>> import dftd3.pyscf as d3
> >>> mol = gto.M(
> ...     atom="""
> ...          O  -1.65542061  -0.12330038   0.00000000
> ...          O   1.24621244   0.10268870   0.00000000
> ...          H  -0.70409026   0.03193167   0.00000000
> ...          H  -2.03867273   0.75372294   0.00000000
> ...          H   1.57598558  -0.38252146  -0.75856129
> ...          H   1.57598558  -0.38252146   0.75856129
> ...          """
> ... )
> >>> grad = d3.energy(scf.RHF(mol)).run().nuc_grad_method()
> converged SCF energy = -149.947191000075
> ```
> 
> Or are you looking for something else?

You are right. I didn't notice that dftd3.pyscf has already provided this wrapper.

**Comment by hebrewsnabla** [comment]
> This wrappers are already provided in both `dftd4.pyscf` and `dftd3.pyscf` by using the `energy` and `grad` functions:
> 
> ```python
> >>> from pyscf import gto, scf
> >>> import dftd3.pyscf as d3
> >>> mol = gto.M(
> ...     atom="""
> ...          O  -1.65542061  -0.12330038   0.00000000
> ...          O   1.24621244   0.10268870   0.00000000
> ...          H  -0.70409026   0.03193167   0.00000000
> ...          H  -2.03867273   0.75372294   0.00000000
> ...          H   1.57598558  -0.38252146  -0.75856129
> ...          H   1.57598558  -0.38252146   0.75856129
> ...          """
> ... )
> >>> grad = d3.energy(scf.RHF(mol)).run().nuc_grad_method()
> converged SCF energy = -149.947191000075
> ```
> 
> Or are you looking for something else?

You are right. I didn't notice that dftd3.pyscf has already provided this wrapper.
